#MakeFile
#The MakeFile of my project
#
#@author TangYida

objects = obj\main.o objwindowBase.o
cairoLib = -L library -lcairo
cairoInc = -I include
cOrd = -std=c++0x -Weffc++ -pedantic

#TODO:(happily)make a makefile 





